automation:
  - id: f0ca9ef44d3b606864eea88a4704baf60d33614b
    alias: Export HA config to git repo
    trigger:
      - platform: time_pattern
        hours: "*"
        minutes: 25
    action:
      - service: hassio.addon_start
        data:
          addon: "core_letsencrypt"
