- id: '1644482494645'
  alias: Disable vacuum camera update when docked
  description: ''
  use_blueprint:
    path: PiotrMachowski/disable_vacuum_camera_update_when_docked.yaml
    input:
      vacuum: vacuum.robot_vacuum
      camera: camera.vacuum_map
- id: '1644482497979'
  alias: Disable vacuum camera update when docked
  description: ''
  use_blueprint:
    path: PiotrMachowski/disable_vacuum_camera_update_when_docked.yaml
    input:
      vacuum: vacuum.robot_vacuum
      camera: camera.vacuum_map
  mode: single
- id: '1650353887007'
  alias: Ri's Office Lights
  description: ''
  use_blueprint:
    path: EPMatt/ikea_e1524_e1810.yaml
    input:
      integration: Zigbee2MQTT
      controller_entity: sensor.ikea_remote_action
      helper_last_controller_event: input_text.ris_office_ikea_remote_last_action
      action_button_center_short:
      - service: light.toggle
        data: {}
        target:
          area_id: ri_s_office
      action_button_up_short:
      - device_id: 27cd6e935587684f83d903e5608ea35c
        domain: light
        entity_id: light.ris_office
        type: brightness_increase
      button_up_long_loop: true
      button_down_long_loop: true
      action_button_up_long: []
      action_button_down_short:
      - device_id: 27cd6e935587684f83d903e5608ea35c
        domain: light
        entity_id: light.ris_office
        type: brightness_decrease
      action_button_down_long: []
      action_button_left_short:
      - service: switch.turn_off
        data: {}
        target:
          area_id: ri_s_office
      action_button_right_short:
      - service: switch.turn_on
        data: {}
        target:
          area_id: ri_s_office
      controller_device: a68268df00fb475e9dbffc45c6de8a6f
- id: '1650766227595'
  alias: Update OpenUV every 30 minutes during the daytime
  trigger:
    platform: time_pattern
    minutes: /30
  condition:
    condition: and
    conditions:
    - condition: sun
      after: sunrise
    - condition: sun
      before: sunset
  action:
    service: openuv.update_data
- id: '1661989262917'
  alias: Control Living Room Lights
  description: ''
  trigger:
  - id: brightness
    platform: state
    entity_id:
    - sensor.living_room_light_dimmer_action
    to:
    - brightness_move_down
    - brightness_move_up
    - brightness_stop
  - id: toggle
    platform: state
    to: toggle
    entity_id:
    - sensor.living_room_light_dimmer_action
  condition: []
  action:
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ trigger.id == ''toggle'' }}'
      sequence:
      - service: light.toggle
        target:
          area_id: living_room
        data:
          transition: 1
    - conditions:
      - condition: template
        value_template: '{{ trigger.id == ''brightness'' }}'
      sequence:
      - service: light.turn_on
        data:
          transition: 0.1
          brightness: '{{ state_attr(''sensor.living_room_light_dimmer_action'', ''brightness'')
            | int }}'
        target:
          area_id: living_room
  mode: queued
