# vim:set ts=2 sw=2 tw=0 et:

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  packages: !include_dir_named packages
  customize: !include customize.yaml
  customize_glob:
    "sensor.*_fire_danger*":
      icon: "mdi:fire"
    "switch.*plug*":
      icon: "mdi:power-socket-au"
  allowlist_external_dirs:
    - /config

recorder:
  db_url: !secret recorder_db
  commit_interval: 30

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - !secret lan_subnet
    - !secret iot_subnet
    - !secret not_subnet

frontend:
  themes: !include_dir_merge_named themes

logger:
  default: warning
  logs:
    homeassistant.loader: error

ffmpeg:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret
  track_new_calendar: false
