# vim:set ts=2 sw=2 tw=0 et:

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  packages: !include_dir_named packages
  customize: !include customize.yaml
  customize_glob:
    "sensor.*_fire_danger*":
      icon: "mdi:fire"
    "switch.*plug*":
      icon: "mdi:power-socket-au"
  allowlist_external_dirs:
    - /config

recorder:
  db_url: !secret recorder_db
  commit_interval: 30
  purge_keep_days: 14

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - !secret docker_subnet
    - !secret lan_subnet
    - !secret iot_subnet
    - !secret not_subnet

frontend:
  themes: !include_dir_merge_named themes

logger:
  default: warning
  logs:
    homeassistant.loader: error
    custom_components.magic_areas: debug

ffmpeg:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
