external_components:
  # - source: github://myhomeiot/esphome-components # ble_gateway
  - source: github://ilarrain/esphome-components # ble_gateway fork with discovery option

esp32_ble_tracker:
  scan_parameters:
    active: false

bluetooth_proxy:

ble_gateway:
  id: blegateway
  discovery: true
  on_ble_advertise:
    then:
      homeassistant.event:
        event: esphome.on_ble_advertise
        data:
          packet: !lambda return packet;

text_sensor:
  - platform: homeassistant
    id: ble_gateway_devices
    entity_id: binary_sensor.ble_gateway
    attribute: devices
    on_value:
      then:
        lambda: id(blegateway).set_devices(x);
