wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # domain: !secret wifi_domain
  fast_connect: true
  #power_save_mode: none
  ap:
    ssid: ${node_name}

captive_portal:
#web_server:
#  port: 80
