substitutions:
  node_name: "athom-plug-55869a"
  friendly_name: "Washing Machine Plug"

packages:
  base: !include common/base.yaml
  plug: !include common/athom-plug.yaml

wifi:
  use_address: 10.10.30.157