substitutions:
  name: "athom-plug-ce0b40"
packages:
  athom.smart-plug: github://athom-tech/athom-configs/athom-smart-plug.yaml
esphome:
  name_add_mac_suffix: false
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
