substitutions:
  node_name: "athom-plug-5586a8"
  friendly_name: "Garden Shed Lights"

packages:
  base: !include common/base.yaml
  plug: !include common/athom-plug.yaml

wifi:
  use_address: 10.10.30.171