substitutions:
  node_name: ble-gateway-2
  friendly_name: Garden Shed BLE Gateway

esphome:
  platform: ESP32
  board: esp32dev

packages:
  base: !include common/base.yaml
  ble: !include common/ble-gateway.yaml
  # ph_260bd: !include common/ph_260bd.yaml

web_server:
  version: 2
  include_internal: true

wifi:
  use_address: 10.10.30.82
