substitutions:
  node_name: ble-gateway-3
  friendly_name: BLE Gateway 3

esphome:
  platform: ESP32
  board: esp32dev

packages:
  base: !include common/base.yaml
  ble: !include common/ble-gateway.yaml

wifi:
  use_address: 10.10.30.120
