homeassistant: true
frontend:
  port: 8099
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://core-mosquitto
  keepalive: 60
  reject_unauthorized: true
  version: 4
serial:
  port: /dev/ttyACM0
  adapter: deconz
devices:
  '0x804b50fffe100ed4':
    friendly_name: IKEA Remote
  '0x00158d0008091c32':
    friendly_name: Bo's Office Door
    debounce: 1
    filtered_attributes: []
    optimistic: true
  '0x00158d00080915bd':
    friendly_name: Ri's Office Door
  '0x00158d0007e7725b':
    friendly_name: Back Door
  '0x00158d0008091b58':
    friendly_name: Front Door
  '0x00158d0007e4c4f2':
    friendly_name: Fridge Door
    debounce: 1
    optimistic: true
  '0x5c0272fffee93bae':
    friendly_name: Bo's Office Motion Sensor
  '0x00124b002359ed4c':
    friendly_name: Ri's Office
  '0xa4c138fda4db2c5e':
    friendly_name: Bo's Office PIR 2
  '0x84b4dbfffe850fda':
    friendly_name: Unused presence sensor
